const scene = (id, part, title, body, object, question, understanding, interaction, next) => ({id,part,title,body,object,question,understanding,interaction,next,motion:object==='structure'?'대상 중심으로 카메라 이동, 외곽 소거, 내부 레이어 공개':'정착 후 상태 변화와 다음 개념으로 연결'});
export const scenes = [
scene('question','컴퓨터의 기억','컴퓨터가 데이터를<br>기억하는 방식','전원을 꺼도 남아 있는 데이터.<br>그 기억은 SSD 어디에 있을까요?','structure','전원을 꺼도 어떻게 기억할까?','전원과 저장 상태는 다르다.','전원 켜기·끄기','SSD 내부에서 저장 영역 찾기'),
scene('ssd','구조 탐험 · SSD','컴퓨터가 데이터를<br>기억하는 방식','SSD 내부로 들어가며<br>데이터가 실제로 저장되는 구조를 살펴봅니다.','structure','SSD 안에서 누가 저장을 담당할까?','Controller는 관리하고 NAND Flash는 비휘발성 저장을 담당한다.','NAND hover·확대','NAND Package'),
scene('package','구조 탐험 · NAND Package','작은 패키지<br>안으로','NAND Package에는 하나 이상의 Die가 있습니다.<br>덮개 안의 반도체 칩을 따라 들어갑니다.','structure','Package 안에는 무엇이 있을까?','Package와 내부 Die는 다른 계층이다.','덮개 열기·Die hover','Die와 Plane'),
scene('die','구조 탐험 · Die','칩 안에도<br>구획이 있습니다','하나의 Die는 Plane으로 나뉩니다.<br>각 Plane에는 많은 Block이 있습니다.','structure','칩 안의 공간은 어떻게 나뉠까?','Die 안에 Plane, Plane 안에 Block이 있다.','Plane·Block hover','Block'),
scene('block','구조 탐험 · Block','지울 때는<br>한 묶음씩','Block은 여러 Page를 묶은 영역입니다.<br>Erase는 이 Block 전체에 적용됩니다.','structure','무엇을 한꺼번에 지울까?','Block이 지우는 단위다.','Page 선택·hover','Page'),
scene('page','구조 탐험 · Page','읽고 쓰는 단위,<br>Page','많은 Cell의 상태를 함께 읽고 기록합니다.<br>Read와 Program의 기본 단위는 Page입니다.','structure','데이터는 어느 단위로 오갈까?','Page 단위 I/O와 Cell의 상태를 연결한다.','Cell hover·확대','Cell'),
scene('cell','Cell의 물리','기억은<br>전하의 상태','절연층에 둘러싸인 저장 영역이 전하를 유지합니다.<br>이 전하가 전류가 흐르기 시작하는 전압, Vth를 바꿉니다.','cell','Cell은 무엇을 기억할까?','전하 → Vth → 구분 가능한 상태로 이어진다.','Floating Gate / Charge Trap·전원 toggle','상태 수와 bit'),
scene('density','Cell의 물리','더 잘게 나누면,<br>더 많이 담습니다','같은 Cell에서 더 많은 Vth 상태를 구분합니다.<br>용량은 늘지만 상태 사이의 여유는 좁아집니다.','density','한 Cell에 여러 bit를 어떻게 저장할까?','SLC/MLC/TLC/QLC는 2/4/8/16개 상태를 구분한다.','SLC·MLC·TLC·QLC toggle','Program'),
scene('program','NAND의 동작 · Program','쓴다는 것은<br>전하를 옮기는 일','Program 전압을 가하면 저장 영역으로 전하가 이동합니다.<br>반복한 펄스와 확인으로 목표 Vth에 접근합니다.','cell','기록할 때 Cell에서 무엇이 변할까?','Program이 전하 상태와 Vth를 바꾼다.','Program 펄스·초기화','Read'),
scene('read','NAND의 동작 · Read','전자를 세지 않고,<br>전류를 봅니다','기준 전압을 가하고 전류가 흐르는지 확인합니다.<br>Vth와 기준 전압의 관계로 저장 상태를 판별합니다.','cell','저장한 상태는 어떻게 읽을까?','기준 전압이 Vth보다 높으면 채널이 도통한다.','기준 전압 slider·저장 상태 toggle','Erase와 overwrite 제약'),
scene('erase','NAND의 동작 · Erase','한 Page만<br>다시 쓸 수는 없습니다','사용한 Page를 자유롭게 덮어쓸 수 없습니다.<br>다시 사용하려면 Block 전체를 Erase해야 합니다.','erase','파일 수정은 어떻게 가능할까?','Page 단위 Read/Program과 Block 단위 Erase의 차이다.','Page 선택·Read·Program·Block Erase','논리 주소와 물리 주소'),
scene('address','Controller와 Software','같은 주소,<br>다른 자리','Host는 LBA를 사용합니다.<br>FTL이 LBA를 실제 NAND 위치인 PPA로 연결합니다.','mapping','Host가 아는 주소가 실제 저장 위치일까?','논리 주소와 물리 주소를 FTL Mapping이 잇는다.','LBA 선택','Out-of-place Update'),
scene('ftl','Controller와 Software · FTL','고치는 대신,<br>새 자리에 씁니다','새 Page에 기록하고 Mapping을 옮깁니다.<br>이전 Page는 더 이상 유효하지 않은 Invalid 상태가 됩니다.','mapping','같은 LBA를 수정하면 무엇이 바뀔까?','새 Page 기록 → Mapping 갱신 → 기존 Page invalid.','LBA 100 수정·초기화','Garbage Collection'),
scene('gc','공간 관리 · Garbage Collection','남길 것만 옮기고,<br>한꺼번에 비웁니다','Valid Page를 먼저 옮겨 보존합니다.<br>그 다음 Block을 지워 다시 쓸 공간을 확보합니다.','mapping','Invalid Page로 가득 찬 공간은 어떻게 되찾을까?','migration과 Mapping 갱신이 Erase보다 먼저다.','수정 반복·GC 실행·단계별 이동 표시','Wear Leveling'),
scene('wear','수명 관리 · Wear Leveling','사용 횟수를<br>나누는 일','Program / Erase가 반복되면 Cell이 마모됩니다.<br>덜 사용한 Block을 선택하고 Bad Block은 제외합니다.','wear','특정 Block만 닳으면 어떻게 될까?','웨어 분산과 불량 블록 제외로 수명을 관리한다.','분산 켜기·끄기·P/E 반복·Bad Block 지정','Retention / Disturb'),
scene('reliability','오류와 복구','기억의 경계는<br>조금씩 흔들립니다','시간이 흐르거나 주변 Cell이 반복해서 읽히면<br>Vth 분포가 달라져 읽는 값에 오류가 생길 수 있습니다.','reliability','저장 상태가 변하면 무엇이 달라질까?','Retention과 Read Disturb가 읽기 판정을 어렵게 한다.','Retention / Read Disturb·변화량 slider','ECC와 Read Retry'),
scene('ecc','오류와 복구 · ECC','여분의 bit로<br>오류를 찾아냅니다','데이터와 함께 저장한 검사 bit로 오류를 찾습니다.<br>복구 한계를 넘으면 다시 읽거나 실패를 보고합니다.','ecc','틀린 bit를 어떻게 바로잡을까?','검사 부호의 제한된 복구 능력과 Read Retry의 역할이다.','bit 뒤집기·ECC 실행·Read Retry','전체 Write 흐름'),
scene('write','전체 흐름 · Write','한 번의 저장에<br>많은 일이 일어납니다','Host의 요청이 FTL과 ECC를 거쳐 NAND로 갑니다.<br>새 Page 기록이 끝나면 Mapping을 확정합니다.','flow','파일 저장 요청은 어디로 갈까?','애플리케이션 요청과 NAND Program을 하나로 연결한다.','Write 단계 진행·다시 실행','전체 Read 흐름'),
scene('read-flow','전체 흐름 · Read','읽을 때도<br>확인하며 돌아옵니다','FTL이 위치를 찾고 NAND가 Page를 읽습니다.<br>ECC 확인을 거친 데이터가 Host로 돌아옵니다.','flow','읽기 요청은 어떤 경로로 돌아올까?','Mapping·물리 읽기·ECC·필요 시 Retry가 연결된다.','Read 단계 진행·Retry 경로 toggle','SSD로 돌아가기'),
scene('ending','탐험을 마치며','작은 전하와,<br>그것을 관리하는 기술','NAND의 물리적 제약을 Controller와 Software가 관리합니다.<br>그래서 우리는 SSD를 안정적인 저장장치처럼 사용합니다.','ending','컴퓨터는 어떻게 데이터를 기억하는가?','전하의 저장과 이를 관리하는 계층이 합쳐져 SSD가 된다.','처음으로·자세히 읽기','Article / Appendix'),
];
export const hierarchy = ['SSD','NAND Package','Die','Block','Page','Cell'];
export const hierarchyScenes = [1,2,3,4,5,6];
export const writeSteps = ['Application','File System','Block I/O','NVMe Command','SSD Controller','FTL · LBA 확인','Free Page 선택','ECC · 부호화','NAND Program','Mapping 갱신','기존 Page Invalid'];
export const writeNotes = ['애플리케이션이 데이터를 저장합니다.','파일의 변경을 블록 요청으로 바꿉니다.','논리 블록 주소와 데이터를 전달합니다.','NVMe Write 명령이 SSD에 도착합니다.','Controller가 요청을 받아 처리합니다.','LBA 100의 기존 위치를 확인합니다.','지워진 새 Page를 예약합니다.','데이터에 검사 bit를 더합니다.','새 Page에 기록하고 성공 여부를 확인합니다.','LBA가 새 Page를 가리키도록 확정합니다.','옛 Page를 Invalid로 표시합니다.'];
export const readSteps = ['Host Read','LBA 확인','FTL Mapping','Physical Page','NAND Read','ECC Decode','Host 반환'];
export const retrySteps = ['Host Read','LBA 확인','FTL Mapping','Physical Page','NAND Read','ECC Decode','Read Retry','ECC 재확인','Host 반환'];
export const readNotes = ['Host가 LBA 100을 요청합니다.','논리 주소를 확인합니다.','Mapping에서 현재 PPA를 찾습니다.','해당 Block과 Page를 선택합니다.','기준 전압으로 Cell 상태를 판정합니다.','검사 bit로 오류를 확인하고 복구합니다.','검증한 데이터를 Host에 반환합니다.'];
export const articleSections = [
['structure','NAND Flash의 구조','SSD의 NAND Package 안에는 하나 이상의 Die가 있습니다. Die는 Plane으로, Plane은 Block으로 나뉘며 Block에는 많은 Page와 Cell이 있습니다. Page는 Read/Program의 기본 단위이고 Block은 Erase 단위입니다.','실제 3D NAND에서는 Cell이 수직으로 쌓이고 문자열(String)로 연결됩니다. 본편은 계층을 이해하기 위한 단순화된 배치입니다. Page 수, 크기, Die 수와 눈금은 특정 제품 사양을 나타내지 않습니다. TLC/QLC에서는 같은 물리 Cell 집합에 여러 논리 Page가 대응할 수 있습니다.','https://www.kioxia.com/en-jp/rd/technology/nand-flash.html'],
['charge','전하, Floating Gate / Charge Trap, Vth','전하 저장 영역과 채널 사이의 절연층은 저장된 전하를 유지하는 데 중요합니다. Floating Gate는 전기적으로 절연된 도체에, Charge Trap은 절연막의 포획 상태에 전하를 저장합니다. 구조가 달라도 전하가 읽기 특성에 영향을 준다는 핵심은 같습니다.','Vth는 전류가 흐르기 시작하는 게이트 전압입니다. 여기서는 Program에 따라 전자 저장량과 Vth가 높아지는 직관적 모델을 사용합니다. 도식의 전자 수와 전압은 상대적인 설명값이며, 실제 3D 셀 단면·전압 파형·영구 보존을 보장하는 모델이 아닙니다.','https://www.kioxia.com/en-jp/rd/technology/nand-flash.html'],
['density','SLC / MLC / TLC / QLC','Cell당 1, 2, 3, 4 bit를 구분하려면 각각 2, 4, 8, 16개 상태가 필요합니다. 전압 창 안에 상태를 더 많이 담으면 상태 간 간격이 좁아져 정밀한 Program과 Read, 더 강한 오류 관리가 중요해집니다.','분포 그래프는 실제 측정 데이터가 아닙니다. 동일 폭을 사용해 비교하고, 상태 번호를 표시합니다. 실제 bit 부호화는 제조사와 방식에 따라 달라지므로 상태 번호를 실제 NAND의 bit 순서로 해석하지 않습니다.','https://www.kioxia.com/en-jp/rd/technology/multi-level-cell.html'],
['operations','Program / Read / Erase와 overwrite','Program은 저장 전하를 변화시키고 목표 상태에 접근하도록 제어합니다. Read는 기준 전압 아래에서의 전류를 감지하는 과정입니다. 본편의 SLC 예에서는 낮은 Vth의 지워진 상태를 1, 높은 Vth의 Program 상태를 0으로 표시합니다.','Read/Program은 Page, Erase는 Block 단위로 설명합니다. 실제 NAND에는 부분 Program, 순서, 여러 단계 Program 등 제품별 제약이 있으므로 임의의 Page를 자유롭게 반복 기록하는 것으로 이해하면 안 됩니다. 변경을 새 Page에 기록하는 방식은 이런 물리 제약을 상위 계층에서 숨깁니다.','https://www.micron.com/sales-support/sales/faqs'],
['ftl','FTL, LBA / PPA와 Mapping','Host가 사용하는 LBA는 논리 블록 주소입니다. Controller의 FTL은 이 주소와 NAND의 물리 위치 사이를 연결합니다. 동일한 LBA를 수정해도 물리 위치는 달라질 수 있습니다. 새 Page 기록 후 Mapping을 바꾸고 이전 Page를 Invalid로 표시합니다.','본편은 LBA 한 개를 Page 한 개에 대응시킨 교육용 모델입니다. 실제 논리 블록과 NAND Page 크기는 다를 수 있고, Mapping의 세분성·캐시·메타데이터·전원 차단 복구 설계는 더 복잡합니다. Invalid는 데이터가 즉시 물리적으로 지워졌다는 뜻이 아닙니다.','https://www.micron.com/products/storage/nand-flash/choosing-the-right-nand'],
['gc','Garbage Collection','Invalid Page가 있어도 그 자리만 따로 Erase하지 못합니다. GC는 대상 Block의 Valid 데이터를 다른 Free Page에 옮기고 Mapping을 갱신합니다. 남겨야 할 데이터가 없어진 뒤 대상 Block을 Erase하면 전체가 다시 Free가 됩니다.','이 추가 복사는 Host가 요청한 것보다 많은 NAND 쓰기를 유발할 수 있습니다. GC 시뮬레이션은 같은 Mapping 상태를 FTL 화면과 공유하며, 이동 전에 지우지 않도록 순서를 보장합니다. 실제 장치에는 예비 공간, 동시 요청, 정책과 시간 비용이 더해집니다.','https://www.kioxia.com/content/dam/kioxia/shared/business/memory/mlc-nand/asset/productbrief/KIOXIA_Understanding_Garbage_Collection_Tech_Brief.pdf'],
['wear','P/E Cycle, Wear Leveling, Bad Block','Program과 Erase의 반복은 셀의 절연층과 읽기 특성을 변화시킵니다. Wear Leveling은 특정 Block에 사용이 몰리는 것을 줄입니다. 동적 방식은 새 쓰기 위치를 분산하고, 정적 방식은 오래 움직이지 않은 데이터도 이동시켜 사용 편차를 줄일 수 있습니다.','본편의 막대는 수명 예측이 아닌 P/E 횟수 비교입니다. 낮은 사용 횟수 우선 선택만 간단히 보여줍니다. 불량 Block은 생산 단계부터 존재할 수도, 사용 중 생길 수도 있습니다. Bad Block은 사용 대상에서 제외하며, 마모 횟수 하나만으로 불량을 판정하는 것은 아닙니다.','https://www.kioxia.com/content/dam/kioxia/shared/business/memory/mlc-nand/asset/productbrief/KIOXIA_Understanding_Wear_Leveling_Tech_Brief.pdf'],
['ecc','Retention / Disturb, ECC와 Read Retry','Retention은 시간에 따른 저장 특성의 변화이고, Read Disturb는 반복 읽기가 주변의 읽지 않은 Cell 상태에 영향을 주는 현상입니다. ECC는 저장 시 추가한 검사 정보를 이용해 읽은 데이터의 오류를 검출·복구합니다. 복구 능력에는 한계가 있습니다.','8 bit 시뮬레이션은 확장 Hamming (8,4) SECDED를 실제 계산하여 1 bit 오류를 고치고 2 bit 오류를 검출합니다. 최신 SSD의 BCH/LDPC를 재현하지 않습니다. Read Retry는 기준 전압을 바꿔 같은 상태를 다시 판정하는 과정이며, 전하를 복원하거나 모든 오류를 보장해서 고치는 기능이 아닙니다.','https://www.kioxia.com/content/dam/kioxia/shared/business/memory/mlc-nand/asset/productbrief/KIOXIA_Understanding_ECC_Tech_Brief.pdf'],
['flow','전체 Read / Write와 Controller','Write는 Host의 LBA와 데이터를 받아 새 물리 공간을 선택하고 검사 정보를 더해 Program합니다. 성공 후 Mapping을 확정하고 이전 위치를 Invalid로 표시하는 순서를 보여줍니다. Read는 Mapping으로 위치를 찾고 읽은 데이터의 ECC를 확인한 뒤 Host로 반환합니다.','여기서는 이해를 위해 직렬 단계로 나눴습니다. 실제 Controller는 여러 채널과 Die에 요청을 병렬 처리하고, 캐시·스케줄링·메타데이터 일관성·복구·GC를 함께 관리합니다. NAND가 물리적 상태를 담고, Firmware가 그 제약을 관리한다는 것이 전체 흐름의 핵심입니다.','https://www.micron.com/products/storage/nand-flash/choosing-the-right-nand'],
];
