export type SceneKind = "boundary"|"learning"|"probability"|"generation"|"context"|"attention"|"transformer"|"scale"|"runtime"|"tool"|"execution"|"result"|"loop"|"harness"|"incident";
export type ArticlePage = { id:string; title:string; presentation:string; article:string[]; scene:SceneKind; references?:string[] };

export const pages: ArticlePage[] = [
  {id:"boundary",scene:"boundary",title:"LLM과 Coding Agent의 경계",presentation:"LLM은 문장과 코드를 생성하고, Coding Agent는 실행 환경을 연결한다.",article:["대규모 언어 모델(LLM)은 문장과 코드를 생성한다. Coding Agent는 여기에 더해 저장소를 탐색하고, 파일을 수정하고, 명령어와 테스트를 실행한다. 두 시스템의 차이를 이해하려면 모델 자체의 능력과 모델 밖에서 실행되는 기능을 구분해야 한다.","이 글은 언어 모델의 학습과 생성 원리에서 출발한다. 이어서 Transformer가 문맥을 처리하는 방법, Tool Calling이 모델의 출력을 행동 요청으로 표현하는 방법, Runtime이 요청을 실행하고 결과를 다시 모델에 전달하는 방법을 순서대로 살펴본다. 이 과정을 연결하면 LLM과 Coding Agent의 관계를 하나의 구조로 설명할 수 있다."]},
  {id:"learning",scene:"learning",title:"모델은 예측 오차를 줄이며 학습한다",presentation:"입력 → 예측 → 정답 비교 → Loss → Weight Update",article:["신경망 모델의 학습은 입력에 대한 예측을 만들고, 예측과 정답의 차이를 줄이는 과정이다. 개와 고양이를 구분하는 이미지 분류 모델이라면 입력 이미지를 처리한 뒤 각 클래스의 점수를 계산한다. 정답이 고양이인데 개의 점수를 더 높게 계산했다면 손실이 커지고, 학습 과정은 이 손실이 작아지는 방향으로 모델의 가중치를 조정한다.","모델은 사람이 작성한 분류 규칙을 그대로 저장하지 않는다. 많은 학습 데이터에서 예측과 수정을 반복하면서 입력의 어떤 패턴이 특정 출력과 연결되는지를 가중치에 반영한다. 언어 모델도 기본적으로 같은 방식으로 학습하지만, 예측해야 하는 대상이 개나 고양이 같은 소수의 클래스가 아니라 언어를 구성하는 토큰이라는 점이 다르다."]},
  {id:"probability",scene:"probability",title:"언어 모델은 다음 토큰의 확률을 계산한다",presentation:"Context에서 Vocabulary 후보의 Logit을 계산해 확률 분포로 바꾼다.",article:["언어 모델은 텍스트를 토큰 단위로 처리한다. 토큰은 단어 전체일 수도 있고, 단어의 일부나 문장부호일 수도 있다. 모델이 사용할 수 있는 토큰의 전체 목록을 Vocabulary라고 한다. 모델은 앞에 주어진 토큰들을 바탕으로 Vocabulary의 각 토큰이 다음 위치에 등장할 가능성을 계산한다.","예를 들어 서버가 요청을 처리하지 못해 500이라는 문맥 뒤에는 오류, 응답, 상태와 같은 여러 후보가 올 수 있다. 모델은 각 후보에 점수인 Logit을 만들고, 이를 확률 분포로 변환한다. 학습할 때는 실제 다음 토큰의 확률이 높아지도록 가중치를 조정한다. 따라서 언어 모델의 기본 학습 목표는 주어진 문맥에서 다음 토큰을 더 정확하게 예측하는 것이다."]},
  {id:"generation",scene:"generation",title:"반복된 예측이 문장과 코드를 만든다",presentation:"선택된 Token은 Context 뒤에 더해지고, 다음 예측의 입력이 된다.",article:["텍스트 생성 과정에서도 모델은 다음 토큰의 확률을 계산한다. 생성 규칙에 따라 토큰 하나가 선택되면 그 토큰을 기존 문맥 뒤에 붙이고, 늘어난 문맥으로 다시 다음 토큰을 예측한다. 이 자기회귀 과정을 반복하면 한 문장에서 긴 문서와 코드까지 생성할 수 있다.","항상 확률이 가장 높은 토큰만 선택해야 하는 것은 아니다. Temperature와 Sampling 설정에 따라 다른 후보가 선택될 수 있으며, 선택된 토큰은 이후의 모든 예측에 영향을 준다. 출력의 길이와 형태가 달라져도 기본 연산은 같다. LLM이 만드는 긴 응답은 다음 토큰 예측을 반복한 결과다."]},
  {id:"context",scene:"context",title:"다음 토큰을 정하려면 문맥을 처리해야 한다",presentation:"먼 변수 선언과 현재 사용 위치의 관계도 다음 예측에 필요하다.",article:["다음 토큰은 바로 앞 Token만으로 정해지지 않는다. 자연어에서는 앞 문장의 주어와 논지가 필요하고, 코드에서는 변수 선언, 함수의 반환형, 조건문의 범위처럼 멀리 떨어진 정보가 현재 위치의 의미를 결정한다. 언어 모델의 성능은 입력에 포함된 정보 중 현재 예측에 필요한 관계를 얼마나 적절하게 반영하는지에 크게 좌우된다.","Transformer 이전에 널리 사용된 RNN 계열 모델은 Token을 순서대로 처리하며 이전 상태를 다음 단계로 전달했다. 이 방식은 순서 정보를 다루는 데 적합했지만, 멀리 떨어진 Token 사이의 관계를 유지하기 어렵고 여러 위치의 연산을 동시에 처리하기도 어려웠다. Transformer는 Token 사이의 관계를 계산하는 방식을 바꾸면서 이 제약을 줄였다."]},
  {id:"attention",scene:"attention",title:"Self-Attention은 관련 토큰의 정보를 모은다",presentation:"현재 Token의 Query가 다른 Token의 Key와 관련도를 계산하고 Value를 모은다.",article:["Self-Attention에서는 각 Token이 같은 입력 안의 다른 Token들과 얼마나 관련되어 있는지를 계산한다. 현재 Token을 해석하는 데 중요한 Token에는 높은 가중치를 주고, 관련성이 낮은 Token에는 낮은 가중치를 준다. 그 결과 각 Token의 표현에는 현재 문맥에서 필요한 다른 위치의 정보가 함께 반영된다.","이 계산에는 Query, Key, Value가 사용된다. Query는 현재 Token이 어떤 정보를 찾는지를, Key는 각 Token이 어떤 정보와 연결될 수 있는지를 나타낸다. Query와 Key로 관련도를 계산한 뒤 그 가중치에 따라 Value를 합친다. 이 구조에서는 가까운 Token과 멀리 떨어진 Token을 같은 방식으로 비교할 수 있다."]},
  {id:"transformer",scene:"transformer",title:"Transformer는 Attention을 중심으로 문맥을 처리한다",presentation:"병렬 계산과 Causal Mask가 Decoder 중심 언어 모델의 입력 규칙을 만든다.",article:["2017년 발표된 「Attention Is All You Need」는 순환 구조 없이 Attention을 중심으로 입력을 처리하는 Transformer를 제안했다. Transformer는 여러 Token 위치의 계산을 병렬로 수행할 수 있어 대규모 데이터로 모델을 학습하기에 유리했다. 원 논문은 기계 번역을 위한 Encoder–Decoder 구조를 제시했으며, 이후 언어 모델에는 Transformer의 여러 변형이 사용됐다.","GPT 계열의 자기회귀 언어 모델은 주로 Decoder 중심 구조를 사용한다. 학습 시에는 Causal Mask를 적용해 현재 위치가 뒤에 있는 정답 Token을 미리 보지 못하도록 한다. 따라서 각 위치에서는 앞쪽 문맥만을 사용해 다음 Token을 예측한다. Transformer가 LLM과 동일한 개념은 아니지만, 오늘날 많은 LLM이 다음 Token 예측을 수행하는 기반 구조로 Transformer를 사용한다."],references:["Vaswani et al., Attention Is All You Need, 2017."]},
  {id:"scale",scene:"scale",title:"규모 확장과 후속 학습이 모델의 사용 범위를 넓혔다",presentation:"Pretraining Scale → 다양한 언어 능력 → Post-training → 더 나은 지시 준수",article:["Transformer 기반 언어 모델은 더 많은 Parameter, 더 큰 학습 Data, 더 많은 Training Compute를 사용하며 규모가 커졌다. GPT-3 연구에서는 모델 규모를 확장하면서 별도의 가중치 수정 없이 지시문과 몇 개의 예시만으로 여러 작업을 수행하는 Few-shot 성능이 전반적으로 향상됐다. 대규모 사전학습을 거친 하나의 모델을 요약, 번역, 질의응답, 코드 생성 등 여러 작업에 사용할 수 있게 된 것이다.","규모만 키운다고 사용자의 의도를 안정적으로 따르는 것은 아니다. 이후에는 지시문과 선호 데이터를 이용한 Post-training이 모델의 지시 준수와 응답 형식을 개선하는 데 사용됐다. 답을 내기 전에 중간 Token과 계산을 더 사용하는 추론 방식도 발전했다. 그러나 이런 변화 이후에도 모델이 직접 생산하는 것은 Token이며, 외부 환경에서 행동하려면 별도의 연결 구조가 필요하다."],references:["Brown et al., Language Models are Few-Shot Learners, 2020.","Ouyang et al., Training language models to follow instructions with human feedback, 2022."]},
  {id:"runtime",scene:"runtime",title:"모델의 출력만으로는 환경이 바뀌지 않는다",presentation:"MODEL은 출력을 생성하고, RUNTIME이 검증·실행하며, ENVIRONMENT가 상태를 바꾼다.",article:["LLM은 코드와 명령어를 텍스트로 작성할 수 있지만, 텍스트를 생성했다는 사실만으로 파일이 수정되거나 프로그램이 실행되지는 않는다. 모델은 입력된 Context를 바탕으로 출력을 생성할 뿐이며, 로컬 파일 시스템이나 데이터베이스, 브라우저에 임의로 접근하지 않는다.","실제 행동에는 모델과 환경 사이를 연결하는 실행 계층이 필요하다. 모델은 어떤 작업이 필요한지 표현하고, Runtime은 그 요청을 검증해 파일 시스템이나 터미널 같은 Environment에서 실행한다. 모델, Runtime, Environment를 구분하면 LLM이 Agent로 동작하는 과정을 구체적으로 설명할 수 있다."]},
  {id:"tool",scene:"tool",title:"Tool Calling은 행동 요청을 구조화한다",presentation:"모델은 실행이 아니라, Runtime이 해석할 구조화된 Tool Call을 생성한다.",article:["Tool Calling은 모델이 사용할 수 있는 도구의 이름, 기능, 입력 형식을 Context에 제공하는 방식이다. 모델은 사용자의 요청을 처리하는 데 도구가 필요하다고 판단하면 일반 문장 대신 구조화된 호출 요청을 생성할 수 있다. 다음은 개념을 단순화한 예시다.","이 출력은 모델이 파일을 읽었다는 뜻이 아니다. 모델은 read_file이라는 도구와 입력값을 Token으로 표현했을 뿐이다. API와 제품에 따라 실제 메시지 형식은 다르지만, 모델이 구조화된 요청을 만들고 외부 실행 계층이 이를 처리한다는 원리는 같다."],references:["Anthropic, Tool use with Claude."]},
  {id:"execution",scene:"execution",title:"Runtime이 요청을 실제 행동으로 바꾼다",presentation:"Tool Call → Schema Validation → Permission → Execute → Result",article:["Runtime은 모델이 생성한 Tool Call에서 도구 이름과 인자를 읽는다. 먼저 해당 도구가 등록되어 있는지, 입력 형식이 올바른지, 현재 권한으로 실행할 수 있는지를 확인한다. 검증을 통과하면 파일을 읽거나 명령어를 실행하고, 성공 결과나 오류를 정해진 형식으로 만든다.","이 계층은 모델의 출력을 운영체제 명령으로 바로 연결하지 않도록 경계를 만든다. 사용할 수 있는 도구와 경로를 제한하고, 위험한 작업에 승인을 요구하며, 실행 시간과 자원 사용량을 통제할 수 있다. 모델이 요청을 선택하는 것과 시스템이 실행 가능 여부를 결정하는 것은 서로 다른 책임이다."]},
  {id:"result",scene:"result",title:"실행 결과는 다시 모델의 입력이 된다",presentation:"Runtime이 결과를 Context 항목으로 만들고, 갱신된 Context 전체가 다음 Model 호출의 입력이 된다.",article:["도구 실행 결과는 대화의 새로운 항목으로 Context에 추가된다. Anthropic API에서는 클라이언트 도구의 결과를 tool_result 블록으로 전달하며, 다른 API도 이름은 다르지만 같은 역할의 입력을 사용한다. 모델은 이 결과를 포함한 전체 Context에서 다시 다음 출력을 생성한다.","파일 내용이 예상과 다르면 다른 파일을 검색할 수 있고, 명령어가 실패하면 오류 메시지를 바탕으로 인자나 접근 방법을 바꿀 수 있다. 모델이 환경을 직접 감지하는 것은 아니다. Runtime이 환경의 상태를 텍스트나 구조화된 데이터로 변환해 전달하고, 모델은 전달받은 정보 안에서 다음 행동을 선택한다."],references:["Anthropic, How tool use works."]},
  {id:"loop",scene:"loop",title:"모델과 도구의 반복 호출이 Agent Loop를 만든다",presentation:"Goal + Context → Model → Tool Call → Runtime → Tool Result → Updated Context",article:["한 번의 Tool Call만으로 끝나지 않는 작업에서는 모델 호출과 도구 실행을 반복한다. Runtime은 목표, 대화 기록, 도구 결과를 포함한 Context를 모델에 보내고, 모델은 최종 답변 또는 새로운 Tool Call을 생성한다. Tool Call이 나오면 Runtime이 실행 결과를 Context에 추가한 뒤 모델을 다시 호출한다. 이 반복을 Agent Loop라고 부를 수 있다.","실제 Agent는 반복문 외에도 작업 상태와 종료 조건을 관리해야 한다. 목표가 달성됐는지, 오류 후 재시도가 필요한지, 허용된 횟수와 비용을 넘지 않았는지 판단해야 한다. ReAct 연구는 언어 모델이 추론에 해당하는 출력과 외부 환경을 향한 행동을 번갈아 생성하는 구조를 제시했다. 현재의 Agent 시스템은 제품마다 구현이 다르지만, 모델의 선택과 환경의 결과를 반복적으로 연결한다는 공통 구조를 가진다."],references:["Yao et al., ReAct: Synergizing Reasoning and Acting in Language Models, 2022."]},
  {id:"harness",scene:"harness",title:"Coding Agent는 개발 작업을 위한 Harness를 결합한다",presentation:"개발 작업의 결과는 Model뿐 아니라 Context, Tools, Permissions, Sandbox, Validation에 좌우된다.",article:["Coding Agent는 Agent Loop에 코드 작업에 필요한 도구와 제어 기능을 결합한다. 저장소에서 파일을 탐색하고, 관련 코드를 읽고, 변경 사항을 적용하고, 빌드·테스트·정적 분석 명령을 실행할 수 있어야 한다. 또한 긴 작업 중 어떤 코드와 로그를 Context에 유지할지 선택하고, 변경된 파일과 테스트 결과를 작업 상태로 관리해야 한다.","이 실행 구조를 Agent Harness라고 부르기도 한다. Claude Code와 Codex 같은 Coding Agent 제품은 모델뿐 아니라 파일 도구, 셸 실행, Context 관리, 권한 정책, 샌드박스와 검증 절차를 함께 제공한다. 같은 모델을 사용하더라도 Harness가 어떤 정보를 제공하고 어떤 행동을 허용하며 결과를 어떻게 검증하는지에 따라 실제 작업 결과가 달라질 수 있다."],references:["Anthropic, Claude Code overview.","OpenAI, Introducing Codex, 2025."]},
  {id:"incident",scene:"incident",title:"백엔드 예외 해결 과정에서 구조를 확인할 수 있다",presentation:"READ LOG → SEARCH CODE → REPRODUCE → PATCH → TEST → VERIFY",article:["백엔드 API에서 NullPointerException이 발생했다고 가정해 보자. Coding Agent는 먼저 서버 로그에서 예외 메시지와 Stack Trace를 확인한다. 이어서 예외가 발생한 파일과 호출 경로를 검색하고, 어떤 입력이나 상태에서 null이 전달됐는지 관련 코드를 따라가며 확인한다. 여기까지의 파일 조회와 코드 검색은 모델이 선택한 Tool Call을 Runtime이 실행한 결과다.","원인을 확인한 뒤에는 실패 상황을 재현하는 테스트를 작성하거나 기존 테스트를 실행한다. 수정이 필요하면 주변 로직과 기존 동작을 확인한 뒤 코드를 변경하고, 같은 테스트를 다시 실행해 예외가 해결됐는지 검증한다. 테스트가 실패하면 그 결과가 다시 Context에 들어가고, 모델은 오류를 바탕으로 다음 수정이나 추가 조사를 선택한다.","이 과정에서도 LLM의 기본 동작은 다음 Token 생성이다. 파일 조회, 코드 수정, 명령어 실행은 Runtime과 도구가 담당하고, 실행 결과가 다시 모델의 입력으로 전달되면서 여러 단계의 작업이 이어진다. Coding Agent는 LLM의 언어 처리 능력을 개발 환경에 연결한 시스템이며, 그 성능은 모델뿐 아니라 Context 관리, 도구 설계, 권한 통제와 검증 절차에도 의존한다."],references:["OpenAI, Unrolling the Codex agent loop, 2026."]}
];

export const appendix = {title:"부록 · Runtime handoff",presentation:"Model Output → Tool Request → System Boundary → Local Runtime",article:"이 삽화는 구조화된 Model Output이 Tool Request로 표현되고, System Boundary를 넘어 Local Runtime으로 전달되는 관계를 보여준다. 파일·터미널·검증 도구는 Model이 아니라 실행 권한을 가진 Runtime에 연결된다."};
